### ISSUE TITLE
Swagger Doc - No operations defined in spec!

### ISSUE THREAD

**Issue by coroo** [gmarokov/node-fastify-mongo-api#5]
Hi @gmarokov , thank you for this great starter template.
Unfortunately, I have an error when try running the documentation:

<img width="1337" alt="Screen Shot 2020-10-27 at 14 49 52" src="https://user-images.githubusercontent.com/13533557/97272005-e358ab00-1863-11eb-975f-089e33e37606.png">

Can you help me to resolve this issue?

**Comment by gmarokov** [comment]
@coroo thanks for the PR. It's already merged.
